version: '2' # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 250
  method-lines:
    config:
      threshold: 25
  similar-code:
    enabled: false
plugins:
  duplication:
    enabled: true
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - 'dist/'
  - '**/node_modules/'
  - '**/test/'
  - '**/*.d.ts'
