matrix:
  include:
    - language: node_js
      code_climate:
        repo_token:
           secure: a84e50756a52ef762a1a81bb3bbc3fa62ff2ac85db28990a8edaf5f3790b2c72
      node_js:
        - 'stable'
        - 'lts/*'
      before_script:
        - npm install codeclimate-test-reporter nyc -g
      script:
        - ./node_modules/.bin/nyc --reporter=lcov npm test
      after_script:
        - codeclimate-test-reporter < ./coverage/lcov.info
